### ISSUE TITLE
Hashes values in properties

### ISSUE THREAD

**Issue by wesleycoder** [stylus/stylus#2010] opened 2015-09-14 21:35 UTC
When trying to use the syntax without `:` stylus ignores everything below the statement.
For example:
```
c = {
	white: #fff
}
.card
	background-color c.white
	border-radius 3px
	&+.card
		margin-top 15px
```
In the above code nothing works, stylus gets crazy and thinks that c.white is a class. The output looks like this:
```
.card background-color c.white,
.card+.card{
	/* ... */
}
```
If I put the `:` after `background-color` everything works fine.

**Comment by Panya** [comment] 2015-09-14 21:42
Duplicate of #1405

**Closed by Panya** 2015-09-14 21:42 UTC
