### ISSUE TITLE
Compile-time errors when using undefined variables

### ISSUE THREAD

**Issue by jeffijoe** [stylus/stylus#2229] opened 2016-09-27 11:50 UTC
Currently, Stylus does nothing when using an undeclared variable:

```stylus
button
  color: $color
```

I think compile-time errors when using undeclared variables would be nice - if anything behind a flag?

**Comment by Panya** [comment] 2016-09-27 11:53
Duplicate of #809

**Closed by Panya** 2016-09-27 11:53 UTC

**Comment by jeffijoe** [comment] 2016-09-27 11:55
@Panya apologies, I did see that issue but it didn't seem it suggested throwing on undefined variables. Any progress on #809?

**Comment by xmedeko** [comment] 2024-06-25 09:24
Duplicate of #811
