### ISSUE TITLE
@block using mixins

### ISSUE THREAD

**Issue by dakal-oleksandr** [stylus/stylus#2197] opened 2016-06-10 20:47 UTC
I tried using mixin in @block and get unexpected result.

Code: 
```
properies(size) {
   width: size
   height: size 
}

test = @block {
  .selector {
    properies: 10px
  }
}

.blocked {
  {test}
}

.mixin {
 properies: 10px
}
```

Result: 
```
.blocked .selector {
  height: 10px;
}
.mixin {
  width: 10px;
  height: 10px;
}
```
Example demonstrate that mixin include only last property when using inside @block.

**Comment by Panya** [comment] 2016-06-13 15:26
Duplicate of #1917

**Closed by Panya** 2016-06-13 15:26 UTC
