### ISSUE TITLE
Passing hashes to a function [Question]

### ISSUE THREAD

**Issue by JustPepper** [stylus/stylus#2208] opened 2016-07-11 05:09 UTC
```
btn(foo)
    .btn
        color foo["bar"]
        background foo["baz"]

foo = {
  bar: baz,
  baz: raz
}


btn(foo)
```
Can you guys help me with this?.. what im doing wrong here? because if i just put for example color settings["bar"] but when i add background settings["baz"] i get this

```
   29|     .btn
   30|         color settings["bar"]
   31|         background settings["baz"]
   32| 
   33| foo = {
-------^
   34|   bar: baz,
   35|   baz: raz
   36| }

expected "indent", got "outdent"

    at Parser.error (/mnt/shared/lib/node_modules/stylus/lib/parser.js:259:11)
    at Parser.expect (/mnt/shared/lib/node_modules/stylus/lib/parser.js:287:12)
    at Parser.block (/mnt/shared/lib/node_modules/stylus/lib/parser.js:845:12)
    at Parser.selector (/mnt/shared/lib/node_modules/stylus/lib/parser.js:1555:24)
    at Parser.property (/mnt/shared/lib/node_modules/stylus/lib/parser.js:1498:51)
    at Parser.ident (/mnt/shared/lib/node_modules/stylus/lib/parser.js:1453:25)
    at Parser.stmt (/mnt/shared/lib/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (/mnt/shared/lib/node_modules/stylus/lib/parser.js:685:21)
    at Parser.block (/mnt/shared/lib/node_modules/stylus/lib/parser.js:865:21)
    at Parser.selector (/mnt/shared/lib/node_modules/stylus/lib/parser.js:1555:24)
```

**Comment by darsain** [comment] 2016-07-11 08:27
Hashes are one of the reasons why it is currently a best practice to use colons in properties. Without them, Stylus can't differentiate between a selector and property declaration. So try this:

```styl
btn(foo)
    .btn
        color: foo["bar"]
        background: foo["baz"]

foo = {
  bar: baz,
  baz: raz
}


btn(foo)
```

**Comment by Panya** [comment] 2016-07-11 09:01
Duplicate of #1405

**Closed by Panya** 2016-07-11 09:01 UTC
