### ISSUE TITLE
Option to enforce syntax mode

### ISSUE THREAD

**Issue by pkieltyka** [stylus/stylus#1906] opened 2015-05-01 12:53 UTC
It would be nice to have an option that can be passed to stylus via CLI and library that would enforce either the indented or css syntaxes. As multiple developers work on a project, its easy for both syntax's to fall into a project and just cause a mess.

**Comment by Panya** [comment] 2015-05-01 13:10
Duplicate of #1365

**Closed by Panya** 2015-05-01 13:10 UTC
