### ISSUE TITLE
text-align: center compiles to text-align: j-center

### ISSUE THREAD

**Issue by hajzso** [stylus/stylus#2204] opened 2016-07-05 02:07 UTC
I'm not sure what's causing this, It started happening today. I use roots with accord. Now I realised it might have been wiser to post it there as stylus hasn't been updated in a while, but the issue is open now so maybe someone can help here.

**Comment by Panya** [comment] 2016-07-05 04:19
Duplicate of #1904 (try to update Jeet).

**Closed by Panya** 2016-07-05 04:19 UTC
