### ISSUE TITLE
Consecutive nested @media break bubbling

### ISSUE THREAD

**Issue by maranomynet** [stylus/stylus#1882] opened 2015-03-31 15:36 UTC
[According to the docs](http://learnboost.github.io/stylus/docs/media.html#nested-media-queries) this code:

```Stylus
@media screen
    .foo
        @media (max-width: 499px)
            width: 200px;
        @media (min-width: 500px)
            width: 50%;
        @media (min-width: 900px)
            width: 25%;
``` 

Should output:

```CSS
@media screen and (max-width: 499px) {
    width: 200px;
}
@media screen and (min-width: 500px) {
    width: 50%;
}
@media screen and (min-width: 900px) {
    width: 25%;
}
```

But instead [outputs](http://learnboost.github.io/stylus/try.html) this weirdness:

```CSS
@media screen {
    @media screen and (max-width: 499px) and (min-width: 500px) {
        .foo .foo {
            width: 50%;
        }
    }
    @media screen and (max-width: 499px) and (min-width: 500px) and (min-width: 900px) {
        .foo .foo {
            width: 25%;
        }
    }
}
@media screen and (max-width: 499px) {
    .foo {
        width: 200px;
    }
}
```

**Comment by Panya** [comment] 2015-03-31 16:28
Yep, looks like a regression in 0.50.0. Thanks for the report. I've fixed it in the `dev` branch. The fix will be in the next release.

**Closed by Panya** 2015-03-31 16:28 UTC
