### ISSUE TITLE
Cannot set property 'lineno' of undefined

### ISSUE THREAD

**Issue by ChapDaddy65** [stylus/stylus#1960] opened 2015-07-23 20:58 UTC
I am using CodeKit as my stylus compiler, but I have tested the terminal compiler as well and I get the this identical error from both programs.

It only started happened here and I have never come across this error before, not sure what or how to fix it. 

```Cannot set property 'lineno' of undefined```

```
/usr/local/lib/node_modules/stylus/bin/stylus:662
              throw err;
                    ^
TypeError: main.styl:337:1
   333| 	background: #E3E3E3
   334| 	padding: 2rem 0
   335| 	margin-bottom: 2rem
   336|
   337| // 4 areas of technology
--------^
   338| // - - - - - - - - - - - - - - - - - - - - - - - - -
   339| #the_four_it_groups
   340| 	margin-bottom: 2rem

Cannot set property 'lineno' of undefined

    at Object.Lexer.advance (/usr/local/lib/node_modules/stylus/lib/lexer.js:242:16)
    at Object.Lexer.lookahead (/usr/local/lib/node_modules/stylus/lib/lexer.js:132:46)
    at Object.Lexer.peek (/usr/local/lib/node_modules/stylus/lib/lexer.js:255:17)
    at Parser.peek (/usr/local/lib/node_modules/stylus/lib/parser.js:322:23)
    at Parser.skip (/usr/local/lib/node_modules/stylus/lib/parser.js:430:33)
    at Parser.skipWhitespace (/usr/local/lib/node_modules/stylus/lib/parser.js:439:10)
    at Parser.parse (/usr/local/lib/node_modules/stylus/lib/parser.js:232:14)
    at Renderer.render (/usr/local/lib/node_modules/stylus/lib/renderer.js:80:22)
    at /usr/local/lib/node_modules/stylus/bin/stylus:656:15
    at fs.js:334:14
```

Here's a larger snippet of my stylus file where the error occurs if you need to see the surrounding code, which is mostly comments for the time being:

```
// #service-list
// 	li
// 		text-align: center

// Vendor Carousel
// - - - - - - - - - - - - - - - - - - - - - - - - -
#vendor_carousel
	background: #E3E3E3
	padding: 2rem 0
	margin-bottom: 2rem

// 4 areas of technology
// - - - - - - - - - - - - - - - - - - - - - - - - -
#the_four_it_groups
	margin-bottom: 2rem
```

Thank you in advance for your time and effort. :)

**Comment by Panya** [comment] 2015-07-23 21:09
Sorry, I can't reproduce this with the latest version of Stylus (0.52.0). Your code example compiles fine. Maybe there is some whitespace symbols that I don't see? Also what version of Stylus are you using?

**Comment by ChapDaddy65** [comment] 2015-07-24 18:52
v0.52.0, installed via homebrew.

According to Sublime Text 3 and the Whitespace highlighter, the only whitespace closest to the problem area is the tab that indents the `margin-bottom: 2rem` rule for the `#the_four_it_groups` ID.

I prefer to use Tabs rather than spaces in my code, and I have Sublime Text convert all spaces to tabs, still no change.

After some more trouble shooting I think it may be code that is farther above in the file, because when I delete the troubled line, it moves the error up one line, where nothing exists. Here's my full .styl file for more troubleshooting, you may find something that I have not yet.

http://pastebin.com/raw.php?i=mUjs5jkA

**Comment by Panya** [comment] 2015-07-24 19:01
I still can't get the error message, but I've got another one:
```
expected "indent", got "eos"
```

It's because you have a selector without indented block at the last line of the file:
```styl
#lets_work_together
```

You can comment it or write with brackets:
```css
#lets_work_together {}
```

**Comment by ChapDaddy65** [comment] 2015-07-24 19:14
Commenting that ID out made both errors go away, Thanks.

I just don't understand why it error'd out above the true trouble line, why a comment line a few lines above an unfinished ID?

**Comment by Panya** [comment] 2015-07-24 21:28
Well, I've spotted a bug in the lexer. We currently have an escaping feature for multiline expressions. You can write:
```styl
body
  background: url(some.png) \
    url(some2.png)
```
And it will work because we're replacing `\\ *\n` to ` ` (removes a new line). But in your file you're using this kind of comments:
```css
/* ======================================== *\
     HOMEPAGE MODULES
\* ======================================== */
```
And with current regexp each `*\<newline>` removes one line from the error message line number :)
I've fixed it in the `dev` branch. The fix will be in the next release. Thanks for the report.

**Closed by Panya** 2015-07-24 21:28 UTC
Labels: w: Unconfirmed
