### ISSUE TITLE
use @extends inside block mixin

### ISSUE THREAD

**Issue by netixpro** [stylus/stylus#2040] opened 2015-11-03 09:48 UTC
Hi team,

I would like to use @extends like this:

```
foo()
    .foo
        {block}

.bar
    color red

+foo()
    @extends .bar
    margin 5px
    font-size 14px
```

But I got an error "Cannot read property 'node' of undefined" on last line font-size 14px
Do you know what am I doing wrong?

It works fine when I remove @extends .bar

Thanks!

p.s: it's processed with "gulp-stylus": "^2.1.0"

**Comment by Panya** [comment] 2015-11-03 12:27
Actually this is a duplicate of #1507. You can use a temporary workaround:
```styl
foo()
    .foo
        {block}

.bar
    color red

+foo()
  &
    @extends .bar
    margin 5px
    font-size 14px
```

**Closed by Panya** 2015-11-03 12:27 UTC
