### ISSUE TITLE
Stylus discontinued?

### ISSUE THREAD

**Issue by geoidesic** [stylus/stylus#2575] opened 2021-01-20 18:09 UTC
Dear team,

I've been told by the makers of Quasar (http://quasar.dev) that Stylus has been discontinued and that they are looking to stop supporting it as a result. 

Is this true? I love Stylus, would be sad to see support for it dropped. Please advise.

**Comment by tukusejssirs** [comment] 2021-01-27 20:04
I wish Stylus will continue being maintained. Alternatively, is there any other similar project that is maintained (besides Stylish)?

**Update:** Sorry for this comment of mine. I’ve thought this repo is home of the source of [Stylus](https://github.com/openstyles/stylus/), a web extension. I have never used Stylus of this repo. 😃

**Comment by aradalvand** [comment] 2021-03-01 16:26
It's sad that such an elegant tool with so much potential is discontinued. Why?!

**Comment by amiut** [comment] 2021-03-29 08:20
Hope it continues, it's such a great project, much much better than sass and less

**Comment by LayZeeDK** [comment] 2021-04-29 07:25
Angular [says goodbye](https://twitter.com/Splaktar/status/1387646440026087425).

**Comment by fgblomqvist** [comment] 2021-05-03 13:56
I emailed @xdan 11 days ago and have yet to receive a response, just FYI. This seems dead indeed (until someone else picks up the flag, if ever).

**Comment by remino** [comment] 2021-06-17 09:30
Indeed, Stylus looks dead. What a shame.

**Comment by markfswe** [comment] 2021-06-23 12:40
Yep. Stylus seems dead. It is not even compatible with modern css. Lots of issues with `min()`, `max()`, `:is`, `:has`, grid templates and other things. CSS to Stylus module also has lots of bugs

**Comment by markfswe** [comment] 2021-06-23 13:08
duplicate of i guess :) #2282

**Comment by piyushchauhan2011** [comment] 2021-06-24 07:58
Oh no I thought it was still going on to make it to 1.0

**Comment by iChenLei** [comment] 2021-08-21 08:24
duplicate #2282

**Closed as completed by iChenLei** 2021-08-21 08:24 UTC
