### ISSUE TITLE
Comment indentation should not affect scoping behaviour; causes unexpected CSS output

### ISSUE THREAD

**Issue by axefrog** [stylus/stylus#2053] opened 2015-11-24 05:24 UTC
I saw some other issues with regards to block scoping and comment indentation, and they appear to have been closed (presumably fixed?) but here are some more that are issues right now, and took me ages to figure out what the heck was going on:

### Base example, working correctly:

```stylus
html.foo
  color red
@media screen
  .bar
    color blue
```

Output:

```css
html.foo {
  color: #f00;
}
@media screen {
  .bar {
    color: #00f;
  }
}
```

### Erroneous example 1:

```stylus
html.foo
  color red
    // a comment
@media screen
  .bar
    color blue
```

Initial selector completely destroyed:

```css
@media screen {
  .bar {
    color: #00f;
  }
}
```

### Erroneous example 2:

```stylus
html.foo
  color red
  // a comment
    // a comment
@media screen
  .bar
    color blue
```

Root selector erroneously appended to media query selector:

```css
html.foo {
  color: #f00;
}
@media screen {
  html.foo .bar {
    color: #00f;
  }
}
```

-----

There might be other comment indentation edge case bugs as well, but it seems to me that if you could have the parser completely disregard comment indentation, these hard-to-find bugs would all magically go away.

**Comment by Panya** [comment] 2015-11-24 05:44
Actually a duplicate of #2011

**Closed by Panya** 2015-11-24 05:44 UTC

**Comment by axefrog** [comment] 2015-11-24 06:20
@Panya is it actually a duplicate? The other one mentions nothing about comments, and also talks about the top selector being indented. I was trying to say that comments should **not** have any effect on block scoping at all, irrespective of how they are indented, and on top of that my examples show erroneous behaviour that is clearly different, both in cause and output, to what is described in #2011.

**Comment by vendethiel** [comment] 2015-11-24 07:47
It's not related to block scoping. By indenting, you made "color red" a block itself (imagine two custom tags), and since this one has no body (only a comment), it's not rendering anything

**Comment by Panya** [comment] 2015-11-24 14:01
@axefrog believe me, it's completely the same problem as in #2011. There is a comment with different indentation in the second example (please read it to the end).
