### ISSUE TITLE
[Bug] Hash pseudo

### ISSUE THREAD

**Issue by nblackburn** [stylus/stylus#2016] opened 2015-09-26 19:41 UTC
I have encountered a bug when following a hash property with a pseudo element

```stylus
class = { row: 'row' }
setting = { gutter: 1em }

.{class.row}
	padding-bottom setting.gutter
	&:last-child
		padding-bottom 0
``` 

Which compiles to the following...

```css
.row padding-bottom setting.gutter,
.row:last-child {
  padding-bottom: 0;
}
```

**Comment by Panya** [comment] 2015-09-26 20:26
Duplicate of #1405. You should write colons in this case.

**Closed by Panya** 2015-09-26 20:26 UTC
