### ISSUE TITLE
Interpolate mixin name

### ISSUE THREAD

**Issue by iboozyvoozy** [stylus/stylus#2127] opened 2016-02-29 13:01 UTC
```
colors = {
    base: gray,
    info: blue
}

for key, val in colors
	.skin-bg-{key}
		background val
	.skin-bd-{key}
		border 1px solid val
```

Now i can use generated classes inside my markup like:
```
div.skin-bg-base.skin-bd-info
```

or inside styles via `@extends`

```
.item-card
	@extends .skin-bg-base
	@extends .skin-bd-info
```

But after reading many of resources that `mixin` is better than `@extends`, i've tried to generate the same name mixins, but no result

```
for key, val in colors
	{'s-bg-' + key}()
		background val
```

or 

```
mixins = {}
for key, val in colors
	mixin[{'s-bg-' + key}]()
		background val
```

not works =(
It is possible in stylus?

**Comment by Panya** [comment] 2016-02-29 13:14
Duplicate of #1783 (it's not possible currently).

**Closed by Panya** 2016-02-29 13:14 UTC

**Comment by iboozyvoozy** [comment] 2016-02-29 13:20
Sorry, thanx
