### ISSUE TITLE
interpolation with quotes

### ISSUE THREAD

**Issue by supersheep** [stylus/stylus#1314] opened 2014-01-03 03:29 UTC
```
a = 1 
&[data-empty-count-for-weekday="{a}"]
    color: red
```

what I wanna see this to be yielded to is:
```
[data-empty-count-for-weekday="1"] {
  color: #f00;
}
```
while what I actually get is:
```
[data-empty-count-for-weekday="{a}"] {
  color: #f00;
}
```

**Comment by kizu** [comment] 2015-09-12 16:33
Duplicate of #728.

**Closed by kizu** 2015-09-12 16:33 UTC
Labels: t: Enhancement
