### ISSUE TITLE
Bug with @extend in @media

### ISSUE THREAD

**Issue by ohardy** [stylus/stylus#1095] opened 2013-08-06 15:53 UTC
This :
```css
$sample
  color #000

a
  @extend $sample

@media (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi)
  strong
    @extend $sample
```

generate this:
```css
a,
strong {
  color: #000;
}
@media (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi) {
}
```

expected this:
```css
a {
  color: #000;
}
@media (-webkit-min-device-pixel-ratio: 1.25), (min-resolution: 120dpi) {
  strong {
    color: #000;
  }
}
```

**Comment by JamenMarz** [comment] 2015-08-11 12:58
As recommended on my issues which was just closed as a duplicate, perhaps there can be some extra functions alternative to `@extend`, I feel like this is how it's supposed to work by design (considering what it renders to).  Maybe a new function like `@clone` or `@inherit` need to be factored in.

**Comment by rosshojo** [comment] 2015-08-17 18:07
+1

**Comment by JamenMarz** [comment] 2015-08-17 18:16
@Panya, What do you think about a new function alternative to `@extend`, like I said previously, feels like that's how it's supposed to work by design, so I think a new function would be better.

**Comment by Dylan-Chapman** [comment] 2015-09-30 18:45
Anybody have a workaround for this? Just ran into it in my project.

**Comment by vio** [comment] 2015-10-02 13:25
@Dylan-Chapman A possible workaround is to dynamically create placeholders for a list of breakpoints and call them dynamically based on `current-media()`

https://gist.github.com/vio/a42c3d7b850a9a4074ad

However, not using this solution on production, I found it too complicated for the limited number of cases I had.

**Comment by kizu** [comment] 2016-02-11 19:59
Closing as a duplicate of #669

**Closed by kizu** 2016-02-11 19:59 UTC
Labels: t: Bug
