### ISSUE TITLE
@extending in @media queries

### ISSUE THREAD

**Issue by JamenMarz** [stylus/stylus#1972] opened 2015-08-11 09:19 UTC
The following:

```stylus
.foo
  padding 10px

.bar
  width 100px
  @media (max-width 750px)
    @extend .foo
    width 100%
```

Renders:

```css
.foo, .bar {
  padding: 10px;
}
.bar {
  width: 100px;
}
@media (max-width: 750px) {
  .bar {
    width: 100%;
  }
}
```

But, I was expecting `.bar` to only extend `.foo`'s properties inside the query.  (This also happens if the `@media` query isn't bubbled, doesn't matter)

Perhaps we can make another function to clone properties, like `@clone` or `@inherit` rather than extend them for scenarios like this one.

For instance:

```stylus
.foo
  padding 10px

.bar
  width 100px
  @media (max-width 750px)
    @inherit .foo
    width 100%
```

Would render:

```css
.foo {
  padding: 10px;
}
.bar {
  width: 100px;
}
@media (max-width: 750px) {
  .bar {
    padding: 10px;
    width: 100%;
  }
}
```

**Comment by JamenMarz** [comment] 2015-08-11 09:23
Just for the record, I have made an alternative:

foo = @block {
  padding 10px
}

.pad
  {foo}

**Comment by Panya** [comment] 2015-08-11 10:39
Duplicate of #1095.

**Closed by Panya** 2015-08-11 10:39 UTC
