### ISSUE TITLE
Aliasing + current-property error

### ISSUE THREAD

**Issue by dmitrykiselyov** [stylus/stylus#1881] opened 2015-03-30 18:53 UTC
Aliasing + **current-property** yielding an error: "Maximum stylus call stack size exceeded"

```stylus
something()
  if current-property
    add-property('bar', 1)
    s('bar')

a = something

body
  foo a()
```

```
    5|
    6| a = something
    7|
    8| body
    9|   foo a()
--------------^
   10|

Maximum stylus call stack size exceeded
```

Thanks for the Stylus. I :heart: it.

**Comment by Panya** [comment] 2015-03-30 20:42
Thanks for the report. Duplicate of #1351

**Closed by Panya** 2015-03-30 20:42 UTC
