### ISSUE TITLE
`for` html attribute breaks compiler

### ISSUE THREAD

**Issue by billymoon** [stylus/stylus#1897] opened 2015-04-18 10:05 UTC
A css selector like this will break the compiler

    label[for="firstname"]
      clear both

using normal css does not help

    label[for="firstname"] {
      clear: both;
    }

I am assuming the compiler thinks the "for" is the start of a loop when in fact it is a valid attribute name of the label HTML tag.

**Comment by billymoon** [comment] 2015-04-18 10:07
Originally asked by @mborman [over here](https://github.com/billymoon/Stylus/issues/60)

**Comment by Panya** [comment] 2015-04-18 12:46
What version of Stylus do you use? I can't reproduce this with the latest version (0.50.0). You can try your example at CodePen or http://learnboost.github.io/stylus/try.html to make sure that everything is working fine.

**Comment by Panya** [comment] 2015-04-18 14:12
Actually, I cannot reproduce this with Stylus package for ST too. So, I'm closing this issue.

**Closed by Panya** 2015-04-18 14:12 UTC
Labels: w: Unconfirmed

**Comment by mborman** [comment] 2015-04-22 02:59
My apologies. First for posting the issue in the wrong project and second because I was indeed running an older version (0.42.3). I had copied some dependencies from another project and was _sure_ I updated the versions... It is what we think we know that keeps us from learning.

Thanks for the response and sorry for wasting your time. 

Cheers,
