### ISSUE TITLE
Is there any way to nest properties ?

### ISSUE THREAD

**Issue by Pandahisham** [stylus/stylus#2037] opened 2015-10-24 17:11 UTC
something like this ?

```
h1 {

   text: {

          align: 'left';

          transformation: 'capatalize';

          indent: 20px;

        }

}
```

**Comment by Pandahisham** [comment] 2015-10-24 17:12
is there any gitter channels ?

**Comment by Panya** [comment] 2015-10-24 17:21
No, this is not possible in Stylus. Duplicate of #848.

**Closed by Panya** 2015-10-24 17:21 UTC
