### ISSUE TITLE
hash parse error?

### ISSUE THREAD

**Issue by nomosyn** [stylus/stylus#1920] opened 2015-05-17 09:25 UTC
case 1: This throws an error:
```
header-s = {
  height: 56px
}

header
  height header-s.height
  z-index 2
  position fixed
```

case 2: This does not throw an error:
```
header-s = {
  height: 56px
}

header
  height: header-s["height"];
  z-index 2
  position fixed
```

Is case 1 supposed to throw an error?

**Comment by Panya** [comment] 2015-05-17 12:01
Duplicate of #1405

**Closed by Panya** 2015-05-17 12:01 UTC

**Comment by Emil14** [comment] 2016-02-24 00:39
try this:
`height: header-s.height`
