### ISSUE TITLE
Nesting with `&` should put sub-selectors in the right order

### ISSUE THREAD

**Issue by mattbasta** [stylus/stylus#1052] opened 2013-06-18 23:18 UTC
```
p:before {
  &.bar {
    color: red
  }
}
```
It's expected that the above code would produce the following:
```css
p.bar:before {
  color: red;
}
```

Instead, it produces

```css
p:before.bar {
  color: red;
}
```

...which is invalid and will never match anything.

Stylus should order selectors within a simple selector such that they are in a valid order.

**Comment by kizu** [comment] 2016-02-11 19:56
Closing as a duplicate of #434

**Closed by kizu** 2016-02-11 19:56 UTC
Labels: t: Feature
