### ISSUE TITLE
Bug pushing into empty array

### ISSUE THREAD

**Issue by sevenupcan** [stylus/stylus#1909] opened 2015-05-04 22:32 UTC
When I try and push into an empty array, the first item isn't being returned as I would expect.

```stylus
oldArray = 'tablet'  20px 1em,
		  'phone' 	 40px 2em,
		  'desktop'  60px 2em

newArray = ()

for item in oldArray
    push(newArray, item)

for item in newArray
    p(item)
```

It comes out as:

```stylus
inspect: 'tablet'
inspect: 20px
inspect: 1em
inspect: 'phone' 40px 2em
inspect: 'desktop' 60px 2em
```

Notice how the first item is split over 3 items.

What's the correct or best way to push into a new array?

**Comment by sevenupcan** [comment] 2015-05-04 22:37
Just realised I think this may be the same as #1066

**Comment by Panya** [comment] 2015-05-04 22:41
Yep, duplicate of #1066

**Closed by Panya** 2015-05-04 22:41 UTC
