### ISSUE TITLE
Indented comments cancel out rule on preceding line

### ISSUE THREAD

**Issue by drbr** [stylus/stylus#2106] opened 2016-02-03 21:32 UTC
If a rule set contains a single-line comment, indented from the rest of the rule set, it causes the preceding rule to disappear from the output CSS. This does not happen if the comment is not indented.

Input stylus:

    #comment-next-line
      background-color limegreen
      color red
      // This comment is not indented
      text-decoration underline

    #comment-next-line-indented
      background-color limegreen
      color red
        // This comment is indented
      text-decoration underline

Output CSS:

    #comment-next-line {
      background-color: #32cd32;
      color: #f00;
      text-decoration: underline;
    }
    #comment-next-line-indented {
      background-color: #32cd32;
      text-decoration: underline;
    }

A few more cases are shown in this Codepen: http://codepen.io/anon/pen/vLzgzx

**Comment by drbr** [comment] 2016-02-03 21:54
I encountered this issue while trying to comment something like the following:

    position absolute // putting this style here
                      // because of a funny edge case
    padding 6px

This definitely seems like a trap into which many people might unsuspectingly fall.

**Comment by Panya** [comment] 2016-02-04 06:30
Duplicate of #2011

**Closed by Panya** 2016-02-04 06:30 UTC
