### ISSUE TITLE
Space between mixin's name and braces breaks stylus

### ISSUE THREAD

**Issue by a-x-** [stylus/stylus#2089] opened 2016-01-21 17:35 UTC
... and it's Bad!

Is it theoretical possible fixed?

```
mixin() <--- no mixin ()
    .bar
        {block}

+mixin() <--- no mixin ()
    .foo
        left: 0px
```

**Comment by Panya** [comment] 2016-01-21 17:45
Duplicate of #374.

**Closed by Panya** 2016-01-21 17:45 UTC
