### ISSUE TITLE
Can't escape "\" in strings

### ISSUE THREAD

**Issue by dapetcu21** [stylus/stylus#1913] opened 2015-05-08 10:24 UTC
This makes it impossible for me to write absolute windows paths:
```
@import "c:\nothing\of\the\kind\works"
@import "c:\\this\\does\\not\\work\\as\\well"
```
It interprets `\n` as a newline and `\\` as two backslashes

My current workaround is
```
@import "c:\" + "this\" + "works"
```

Probably related to #1522

**Comment by Panya** [comment] 2015-05-08 11:37
Duplicate of #1522

**Closed by Panya** 2015-05-08 11:37 UTC
