### ISSUE TITLE
Any ways to allow optional @import file ?

### ISSUE THREAD

**Issue by SamHwang1990** [stylus/stylus#2041] opened 2015-11-06 11:21 UTC
Hi~~~
Is there any ways to allow optional @import file like less?
The mainly purpose of this demand is to let stylus to import a file which may be not existed without throwing error.

**Comment by Panya** [comment] 2015-11-06 11:32
Duplicate of #1872

**Closed by Panya** 2015-11-06 11:32 UTC

**Comment by SamHwang1990** [comment] 2015-11-06 11:48
Thank you for helping~~~
