### ISSUE TITLE
Bug: css syntax

### ISSUE THREAD

**Issue by jasonkuhrt** [stylus/stylus#932] opened 2013-01-01 17:03 UTC
### Error

```

echo '.a{color:red;}  .b{ @extends .a; }' | stylus

/usr/local/lib/node_modules/stylus/bin/stylus:472
      if (err) throw err;
                     ^
ParseError: stdin:1
 > 1| .a{color:red;}  .b{ @extends .a; }
   2| 

expected "}", got "extend .a"

    at Parser.error (/usr/local/lib/node_modules/stylus/lib/parser.js:166:11)
    at Parser.expect (/usr/local/lib/node_modules/stylus/lib/parser.js:194:12)
    at Parser.selector (/usr/local/lib/node_modules/stylus/lib/parser.js:1087:18)
    at Parser.stmt (/usr/local/lib/node_modules/stylus/lib/parser.js:550:26)
    at Parser.statement (/usr/local/lib/node_modules/stylus/lib/parser.js:460:21)
    at Parser.parse (/usr/local/lib/node_modules/stylus/lib/parser.js:145:23)
    at Renderer.render (/usr/local/lib/node_modules/stylus/lib/renderer.js:65:22)
    at Socket.<anonymous> (/usr/local/lib/node_modules/stylus/bin/stylus:471:11)
    at Socket.EventEmitter.emit (events.js:85:17)
    at Pipe.onread (net.js:416:51)

expected "}", got "extend .text-heading1"

```

### Ok
```
echo '.a{color:red;}  .b{ color:red;@extends .a; }' | stylus

.a,
.b {
  color: #f00;
}
.b {
  color: #f00;
}
```

**Comment by kizu** [comment] 2016-02-11 19:47
Seems to be a duplicate of #283, so I'm closing this.

**Closed by kizu** 2016-02-11 19:47 UTC
Labels: t: Bug
