### ISSUE TITLE
Minus sign before variable

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2160] opened 2016-04-03 14:22 UTC
Stylus code:
```styl
a
  $size = 30px
  height: $size
  margin-top: -$size
```

Expected compile result:
```css
a {
  height: 30px;
  margin-top: -30px;
}
```

Actual compile result:
```css
a {
  height: 30px;
  margin-top: -$size;
}
```

In all major programming languages, and also in LESS and SASS, this minus sign works like a charm, but not in Stylus.

It is very inconvinient to replace each minus sign with `-1 *`.

**Comment by iammarkoradak** [comment] 2016-04-03 14:49
You need to add space before variable:

```
a
  $size = 30px
  height: $size
  margin-top: - $size
```

And putting variable in parenthesis also works:

```
a
  $size = 30px
  height: $size
  margin-top: -($size)
```

**Comment by Panya** [comment] 2016-04-03 15:24
Duplicate of #980

**Closed by Panya** 2016-04-03 15:24 UTC
