### ISSUE TITLE
error using background-image without colon and value with dot notation

### ISSUE THREAD

**Issue by jaybekster** [stylus/stylus#2063] opened 2015-12-10 15:30 UTC
I hope my code snippet will explain better than my english
```
$object = {
    level1: {
        color: #fff
    }
}

for $key, $value in $object
    .{$key}
        background-color $value.color // error
        background-color: $value.color // correct
```

**Comment by Panya** [comment] 2015-12-10 20:13
Duplicate of #1405.

**Closed by Panya** 2015-12-10 20:13 UTC
