### ISSUE TITLE
Error "expected indent, got outdent" when using hash values two lines in a row

### ISSUE THREAD

**Issue by tremby** [stylus/stylus#2054] opened 2015-11-26 22:02 UTC
With Stylus 0.52.4 and the following code:

```stylus
$colours = {
	text: white
	background: black
}
body
	color $colours['text']
	background-color $colours['background']
```

I get the following error:

```
/usr/local/lib/node_modules/stylus/bin/stylus:662
              throw err;
                    ^
ParseError: test.styl:8:1
   4| }
   5| body
   6| 	color $colours['text']
   7| 	background-color $colours['background']
   8|
------^

expected "indent", got "outdent"

    at Parser.error (/usr/local/lib/node_modules/stylus/lib/parser.js:257:11)
    at Parser.expect (/usr/local/lib/node_modules/stylus/lib/parser.js:285:12)
    at Parser.block (/usr/local/lib/node_modules/stylus/lib/parser.js:838:12)
    at Parser.selector (/usr/local/lib/node_modules/stylus/lib/parser.js:1546:24)
    at Parser.property (/usr/local/lib/node_modules/stylus/lib/parser.js:1491:51)
    at Parser.ident (/usr/local/lib/node_modules/stylus/lib/parser.js:1446:25)
    at Parser.stmt (/usr/local/lib/node_modules/stylus/lib/parser.js:776:26)
    at Parser.statement (/usr/local/lib/node_modules/stylus/lib/parser.js:683:21)
    at Parser.block (/usr/local/lib/node_modules/stylus/lib/parser.js:858:21)
    at Parser.selector (/usr/local/lib/node_modules/stylus/lib/parser.js:1546:24)
```

The problem goes away if I use a colon to separate key and value in the the `color` rule. It does not go away if I (only) add a colon on the `background-color` rule.

**Comment by Panya** [comment] 2015-11-26 22:07
Duplicate of #1405

**Closed by Panya** 2015-11-26 22:07 UTC

**Comment by tremby** [comment] 2015-11-26 22:09
Thanks.

**Comment by jordyvandomselaar** [comment] 2017-03-02 06:40
The error isn't consistent:
Does error:
`border-color $colors.primary`

Does not error:
`background-color $colors.primary`

It could be a coincidence that one does error whilst the other does not, but it seems weird to me. Also, I can assure you that `border-color $colors.primary` is not a selector, nothing starting with a `$` is.
