### ISSUE TITLE
use undefined function,not throw any error

### ISSUE THREAD

**Issue by sjpsega** [stylus/stylus#1035] opened 2013-05-31 07:52 UTC
for example,
stylus file:
```
.dd
    fun() 
    height:10px
```
and I use nodejs to complie it
```
  var stylus = require('stylus');
  var s = stylus(stylusCode);
  ...
  s.render(function(err, css) {
    if (err) {
      grunt.log.error(err);
      grunt.fail.warn('Stylus failed to compile.');

      callback(css, true);
    } else {
      callback(css, null);
    }
  });
```
in stylus file,"fun" function is undefined,I want it throw a error,but not.

**Comment by kizu** [comment] 2015-09-12 16:18
Closing as a duplicate of #489. Linting and similar tasks shouldn't be hardcoded into Stylus. In 1.0.0 we would expose AST after parsing in a way it could be used by external linters.

**Closed by kizu** 2015-09-12 16:18 UTC
Labels: t: Enhancement

**Comment by chestozo** [comment] 2017-11-17 13:13
It is confusing still )
When you are refactoring and moving your mixins from one place to another you can actually break things and do not notice this because stylus output is totally green )
