### ISSUE TITLE
Mixins can't be called with minimal syntax and named parameters

### ISSUE THREAD

**Issue by ommartin** [stylus/stylus#1944] opened 2015-07-01 13:31 UTC
Just ran into this, and was wondering if that is a bug or done so by design?

The following mixin:

```stylus
foo(bar, baz)
  property bar baz
```

works when called with minimal syntax:

```stylus
div
  foo 1px 2px
```

but the only way you can call it with named parameters is:

```stylus
div
  foo(bar:1px, baz:2px)

// These will not work
div
  foo bar:1px baz:2px
  foo bar:1px, baz:2px
```

**Comment by Panya** [comment] 2015-07-01 14:37
Duplicate of #734.

**Closed by Panya** 2015-07-01 14:37 UTC
