### ISSUE TITLE
watching newly created files 

### ISSUE THREAD

**Issue by Yidada** [stylus/stylus#2276] opened 2017-02-17 10:26 UTC
when use `stylus -w src/*.styl -o src/*.css` to watching the stylus files under a directory and convert them into css files if I add an new file called b.stylus . It will be ignore. Unless I restart the command to compile it again.

**Comment by Panya** [comment] 2017-02-22 09:36
Duplicate of #742

**Closed by Panya** 2017-02-22 09:36 UTC
