### ISSUE TITLE
question about selector()

### ISSUE THREAD

**Issue by bloadvenro** [stylus/stylus#2238] opened 2016-11-02 16:12 UTC
I worked with my favourite stylus and faced with some thing (simplified example):

```
component(name)
  {'.' + name}
    {block}

descendant(name)
  p(selector())
```

If I'll do

```
.MyComponent
  color red
  +descendant(someDescendant)
    color green
```

inspect output for descendant says `.MyComponent`

If I'll do

```
+component(MyComponent)
  color red
  +descendant(someDescendant)
    color green
```

inspect output for descendant says `&`

Is there some way to resolve ampersand? It is very important for me as I want to parse selector later.

**Comment by Panya** [comment] 2016-11-02 16:56
A `block` variable is evaluating in the scope where the mixin was defined. To get the correct value of the selector you can use anonymous functions. E.g.:
```styl
component(name, block)
  {'.' + name}
    block()

descendant(name, block)
  parent = selector()
  /{parent}__{name}
    block()

component(MyComponent, @() {
  color red
  descendant(someDescendant, @() {
    color green
  })
})
```

Duplicate of #1703.

**Closed by Panya** 2016-11-02 16:56 UTC
