### ISSUE TITLE
feature request: executable option on external file

### ISSUE THREAD

**Issue by yukulele** [stylus/stylus#2114] opened 2016-02-14 00:29 UTC
Suggestion: add executable option to set options from external file.

example:
```batch
stylus --options-file ./stylus-option.json
```
with `stylus-option.json` content:
```json
{
  "include": "./src/",
  "out": "./www/",
  "sourcemap": true,
  "watch": true
}
``` 
watch mode, should also watch option file change.

**Comment by Panya** [comment] 2016-02-14 00:35
Duplicate of #296.

**Closed by Panya** 2016-02-14 00:35 UTC
