### ISSUE TITLE
Missing a colon

### ISSUE THREAD

**Issue by pravdomil** [stylus/stylus#2263] opened 2016-12-30 13:47 UTC
Following code
``` stylus
.right { text-align right }
```
throws
``` console
ParseError: index.pug:4:1
   1| div
   2|   padding 1rem 1.25rem
   3|   .right { text-align right }
   4| 
------^

expected "indent", got "outdent"
```
But there nothing wrong with this code right?

**Comment by Panya** [comment] 2016-12-30 13:54
Duplicate of #426.

**Closed by Panya** 2016-12-30 13:54 UTC
