### ISSUE TITLE
absence of space causes parse error.

### ISSUE THREAD

**Issue by charlierudolph** [stylus/stylus#1950] opened 2015-07-10 18:33 UTC
Found a very interesting case where the absence of a space causes a parse error.

Stylus parse succeeds on
```css
@-webkit-keyframes spin {0%{transform:rotate(0)}}
```
Stylus parse errors on
```css
@-webkit-keyframes spin{0%{transform:rotate(0)}}
```
with
```
ParseError: stylus:1:49
   1| @-webkit-keyframes spin{0%{transform:rotate(0)}}
------------------------------------------------------^

expected "indent", got "eos"
```

**Comment by Panya** [comment] 2015-07-10 18:43
Yep,  duplicate of #1945 (already fixed in the `dev` branch). Thanks for the report.

**Closed by Panya** 2015-07-10 18:43 UTC

**Comment by charlierudolph** [comment] 2015-07-10 18:47
Awesome! Any timeframe for the next release?

**Comment by Panya** [comment] 2015-07-10 18:51
@charlierudolph It will be released on the next week.
