### ISSUE TITLE
Fileencoding

### ISSUE THREAD

**Issue by lordnox** [stylus/stylus#256] opened 2011-05-14 11:24 UTC
Hi

Stylus just does not like UCS fileencodings.. just so you know
I'm not sure why my files were encoded like that, but it took me a while to figure out the errors I got.

Thanks for stylus!

**Comment by kizu** [comment] 2016-02-11 19:25
Closing this due to time passed, if someone would like to check if this still reproduces and/or send us a PR fixing this — it would be welcomed!

**Closed** 2016-02-11 19:27 UTC
Labels: t: Enhancement
