### ISSUE TITLE
Possible Hash usage bug

### ISSUE THREAD

**Issue by gandhiShepard** [stylus/stylus#1893] opened 2015-04-14 05:39 UTC
Hashes are rad in Stylus. I love them way more than Sass maps. However, I might have found a Bug in it's implementation.

In Stylus, you don't need the 'colons.' However, if you omit the colon when referencing a hash, you get an error in CodePen. If you try to refresh the page, the error prevents the page from even loading.

I wonder what throws this error?

Just uncomment the commented code and see for yourself. An error will pop up. If you save and refresh the page, the page wont load the pen.

I created a CodPen to show the issue.
http://codepen.io/solvm/pen/QweEyM

**Comment by vendethiel** [comment] 2015-04-14 07:39
Yes, that's an ambiguous parse, that's a duplicate of many other issues.

**Comment by Panya** [comment] 2015-04-14 10:01
Duplicate of #1405

**Closed by Panya** 2015-04-14 10:01 UTC

**Comment by gandhiShepard** [comment] 2015-04-14 12:05
Ugh. Sorry for the duplicate issue. Stylus rocks! Stay awesome!
