### ISSUE TITLE
Document settings

### ISSUE THREAD

**Issue by rstacruz** [stylus/stylus#2031] opened 2015-10-15 18:40 UTC
I was looking at the [API documentation](https://github.com/stylus/stylus/blob/master/docs/js.md) and I was wondering how to set hoisting (`--hoist-atrules`) and CSS import (`--include-css`). I had to dig through the source to find them.

**Comment by Panya** [comment] 2015-10-15 20:05
Duplicate of #1410

**Closed by Panya** 2015-10-15 20:05 UTC
Labels: c: Easy, s: Docs
