### ISSUE TITLE
Handle at-rules with empty block

### ISSUE THREAD

**Issue by eight04** [stylus/stylus#2415] opened 2018-08-22 07:28 UTC
Currently, following code:
```css
@-moz-document domain("example.com") {
  // empty
}
```
would be compiled into:
```css
@-moz-document domain("example.com")
```
This is definitely wrong. Also, there is no line feed after the `domain` function so any code proceeds after `@-moz-document` would be concatenated into the first line. [REPL](http://stylus-lang.com/try.html#?code=%40-moz-document%20domain(%22example.com%22)%20%7B%0A%20%20%2F%2F%20empty%0A%7D%0A%0Abody%20%7B%0A%20%20color%3A%20red%3B%0A%7D)

What is the correct behavior to handle empty at-rules?

1. Remove the entire at-rule definition. This is safe for `@-moz-document`, but it may not work with [unknown at-rules](https://github.com/stylus/stylus/issues/1900).
2. Keep the empty block. This behavior seems to be contrary to the current implementation. https://github.com/stylus/stylus/issues/1900#issuecomment-95254725

Empty at-rules also break nested blocks:
```styl
@foo {
  @bar {
    // empty
  }
}
```
Result:
```css
@foo {
  @bar}
```
[REPL](http://stylus-lang.com/try.html#?code=%40foo%20%7B%0A%20%20%40bar%20%7B%0A%20%20%20%20%2F%2F%20empty%0A%20%20%7D%0A%7D)

**Comment by atilkan** [comment] 2019-02-20 20:26
Duplicate of  https://github.com/stylus/stylus/issues/2427

**Closed** 2019-03-28 16:56 UTC
