### ISSUE TITLE
Issues with comments and indents

### ISSUE THREAD

**Issue by cssmagic** [stylus/stylus#2048] opened 2015-11-19 07:26 UTC
> Node: v4.2.2
> Stylus: v0.52.4

#### Write

```stylus
body
	p a
	// comment
		color red
```

#### Expect

```css
body p a {
	color: red;
}
```

#### Get

`ParseError`

***

#### Write

```stylus
body
		// comment
	p a
		color green
```

#### Expect

`ParseError`

or

```css
body p a {
	color: red;
}
```

#### Get

```css
p a {
	color: red;
}
```

**Comment by Panya** [comment] 2015-11-19 07:28
Duplicate of #2011.

**Closed by Panya** 2015-11-19 07:28 UTC

**Comment by cssmagic** [comment] 2015-11-19 07:36
@Panya 
Thanks for responding.

But I'm not sure **Case 1** is the same as #2011, because the indentation of the comment in **Case 1** is not wrong.
