### ISSUE TITLE
No output for @namespace in CSS

### ISSUE THREAD

**Issue by efficientbaxter** [stylus/stylus#1921] opened 2015-05-19 01:26 UTC
Hi,

somehow **@namespace** gets **ignored**; there is no output at all in the resulting CSS file.

    @namespace svg url(http://www.w3.org/2000/svg)

Even when I use

    @namespace svg "http://www.w3.org/2000/svg"

as suggested in [this old and closed bug report](https://github.com/stylus/stylus/issues/1673) nothing happens.

I'm using the current version 0.51.1

**Comment by Panya** [comment] 2015-05-19 01:35
I can't reproduce it on http://learnboost.github.io/stylus/try.html (0.51.1). Can you show a test case with this bug? Are you sure that you're using the latest version?

**Comment by efficientbaxter** [comment] 2015-05-19 01:57
Yes I'm using the latest ;).

Here you are:
**inline.styl**

    //@import 'settings'
    @import 'base'
    //@import 'type'

**base.styl**

    @namespace svg url(http://www.w3.org/2000/svg);

    body
      background-color $base-background

    svg|svg
      fill currentColor

    svg|.otOomph
      fill $color-contrast

    svg|.otEmbel
      fill $color-accent


**compiling**

    % stylus inline.styl
      compiled inline.css
    %
    %
    % cat inline.css
    body {
      background-color: $base-background;
    }
    svg|svg {
      fill: currentColor;
    }
    svg|.otOomph {
      fill: $color-contrast;
    }
    svg|.otEmbel {
      fill: $color-accent;
    }
    %

**Comment by efficientbaxter** [comment] 2015-05-19 01:59
Interestingly, when I compile **base.styl** directly:

    % stylus base.styl
      compiled base.css
    % 
    % 
    % 
    % cat base.css
    @namespace svg url("http://www.w3.org/2000/svg");
    body {
      background-color: $base-background;
    }
    svg|svg {
      fill: currentColor;
    }
    svg|.otOomph {
      fill: $color-contrast;
    }
    svg|.otEmbel {
      fill: $color-accent;
    }
    % 

it works!

**Comment by Panya** [comment] 2015-05-19 02:29
Yep, confirmed. I've fixed this bug in the `dev` branch. The fix will be in the next release. Thanks for the report.

**Closed by Panya** 2015-05-19 02:29 UTC
Labels: w: Unconfirmed
