### ISSUE TITLE
`$args...` is not the same as `arguments` when passing space-separated arguments

### ISSUE THREAD

**Issue by thybzi** [stylus/stylus#2162] opened 2016-04-04 18:33 UTC
When I'm passing space-separated values to function that accepts `$args...` (rest params), this values are parsed by space in `arguments` automatic variable, but stay solid in `$args`

Is that a bug or whatever?

Stylus code:
```styl
func($args...)
  /* arguments */
  arguments-value: arguments
  arguments-length: length(arguments)
  arguments-type: typeof(arguments)
  arguments-0: arguments[0]
  /* $args */
  args-value: $args
  args-length: length($args)
  args-type: typeof($args)
  args-0: $args[0]
  
.test1
  func(one two three) // passing space-separated list ($args and arguments are different)

.test2
  func(one, two, three) // passing comma-separated list ($args and arguments are similar)
```

Result:
```css
.test1 {
/* arguments */
  arguments-value: one two three;
  arguments-length: 3;
  arguments-type: 'ident';
  arguments-0: one;
/* $args */
  args-value: one two three;
  args-length: 1;
  args-type: 'ident';
  args-0: one two three;
}
.test2 {
/* arguments */
  arguments-value: one two three;
  arguments-length: 3;
  arguments-type: 'ident';
  arguments-0: one;
/* $args */
  args-value: one two three;
  args-length: 3;
  args-type: 'ident';
  args-0: one;
}
```

Codepen for quick reproduce: http://codepen.io/thybzi/pen/grXrqg?editors=0100

**Comment by darsain** [comment] 2016-04-04 18:47
There's a lot more discrepancies and issues with `args...` vs `arguments`. Wrote about some of them in #2150. The flattening workaround in that issue might help you. This pretty much became a boilerplate for a lot of my stylus functions:

```
foo()
  args = flatten(arguments)
```

**Comment by Panya** [comment] 2016-04-04 19:12
Duplicate of #2150

**Closed by Panya** 2016-04-04 19:12 UTC

**Comment by thybzi** [comment] 2016-04-10 14:09
Thanks @darsain for that flatten solution! Anyhow, that all is a little bit weird...
